import "should";
import { generate } from "csv-generate/stream";
import { transform, HandlerCallback, Options } from "../lib/stream.js";

// Collect every chunk of a readable stream
const collect = async <T>(stream: ReadableStream<T>): Promise<T[]> => {
  const chunks: T[] = [];
  const reader = stream.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
  }
  return chunks;
};

// Create a readable stream from an array of records
const readable = <T>(records: T[]): ReadableStream<T> => {
  return new ReadableStream<T>({
    start(controller) {
      for (const record of records) {
        controller.enqueue(record);
      }
      controller.close();
    },
  });
};

describe("API Web Stream Types", function () {
  it("type the elements on both sides of the stream", async function () {
    const stream: TransformStream<[string, number], string> = transform(
      (record: [string, number]) => `${record[0]}:${record[1]}`,
    );
    const output: ReadableStream<string> = readable<[string, number]>([
      ["a", 1],
      ["b", 2],
    ]).pipeThrough(stream);
    const chunks = await collect(output);
    chunks.should.eql(["a:1", "b:2"]);
  });

  it("infer the output element type from the handler return value", async function () {
    const stream = transform((record: string) => record.length);
    const output: ReadableStream<number> = readable<string>([
      "a",
      "bc",
      "def",
    ]).pipeThrough(stream);
    const chunks = await collect(output);
    chunks.should.eql([1, 2, 3]);
  });

  it("support handlers returning a promise", async function () {
    const stream = transform(async (record: string) => {
      await new Promise((resolve) => setTimeout(resolve, 1));
      return record.toUpperCase();
    });
    const output: ReadableStream<string> = readable<string>([
      "a",
      "b",
    ]).pipeThrough(stream);
    const chunks = await collect(output);
    chunks.should.eql(["A", "B"]);
  });

  it("support handlers with a callback", async function () {
    const stream = transform<string, string>(
      (record, callback: HandlerCallback<string>) => {
        setTimeout(() => callback(null, record.toUpperCase()), 1);
      },
    );
    const output: ReadableStream<string> = readable<string>([
      "a",
      "b",
    ]).pipeThrough(stream);
    const chunks = await collect(output);
    chunks.should.eql(["A", "B"]);
  });

  it("type the params option", async function () {
    const stream = transform(
      (record: string, params?: { suffix: string }) =>
        `${record}${params?.suffix}`,
      { params: { suffix: "!" } },
    );
    const output: ReadableStream<string> = readable<string>([
      "a",
      "b",
    ]).pipeThrough(stream);
    const chunks = await collect(output);
    chunks.should.eql(["a!", "b!"]);
  });

  it("accept the documented options", function () {
    const options: Options = {
      parallel: 10,
      params: { my_key: "my value" },
    };
    transform((record: string, params) => [record, params], options);
  });

  it("pipe records generated by csv-generate", async function () {
    const stream = generate({ length: 5, objectMode: false }).pipeThrough(
      transform((record: Buffer) => record.toString().trim()),
    );
    const chunks = await collect(stream);
    chunks.join("\n").split("\n").length.should.eql(5);
  });
});
